### PR TITLE
LoRot

### PR DESCRIPTION
**Pull request by wjun0830**

### CODE REVIEW

**Comment by Manchery** [comment]
Hi, thanks for your contribution! However, can you explain how the paper relates to fundamental research on multi-task learning?

**Comment by wjun0830** [comment]
Multi task learning is known to enhance the performance for all tasks.
In this paper, we provide self supervised task that is utilized in the form
of multi task learning.
In short, we provide a new task for multi task learning where there do not
exist multiple tasks.

2023년 5월 17일 (수) 오후 5:11, Jialong Wu ***@***.***>님이 작성:

**Comment by Manchery** [comment]
Thanks again for your contribution. However, as I understand, this is a paper introducing a self-supervised learning task as an auxiliary task to improve image classification, which, however, is not surprising from the perspective of multi-task learning. Our repo curates papers that advance the fundamental theory or method of MTL. I recommend putting your paper into an awesome list of self-supervised learning.

**Comment by wjun0830** [comment]
Thanks for the feedback!

2023년 5월 19일 (금) 오전 10:57, Jialong Wu ***@***.***>님이 작성:

**Pull request closed without merging**
